---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "uspec/**/*"
